#!/bin/bash
if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    # we don't want odoo to automatically create the database,
    # because this would not initialize unaccent as we want
    createdb -O ${DB_USER} ${DB_NAME}
fi

psql ${db} << EOF
-- cleanup
  CREATE SCHEMA IF NOT EXISTS unaccent_schema; 
  CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA unaccent_schema; 
  CREATE OR REPLACE FUNCTION public.unaccent(text) 
  RETURNS text 
  LANGUAGE sql 
  IMMUTABLE PARALLEL SAFE STRICT 
  AS \$function\$ 
     SELECT unaccent_schema.unaccent('unaccent_schema.unaccent', \$1) 
  \$function\$ ;
EOF

